### ISSUE TITLE
Enhancement request: Join/Leave Event on Users

### ISSUE THREAD

**Issue by ivan98** [line/line-bot-sdk-python#21]
Hi @be-hase / @GuitarSucks 

Currently, Join/Leave events are based on **self**. In other words, when Bot itself joins/leaves a group/room, it will receive the Join/Leave event.

The functionality my application is looking for, is Join/Leave events based on **users**. This means when a new user joins a group/room (in which Bot is present), Bot gets an event (preferably, this event includes userID of new user). This way, Bot can issue welcome message to the group/room, and give introductory instructions to new joins.

Will you consider this enhancement request? Thank you.

**Comment by bottsjw** [comment]
Totally agree @ivan98 having the ability to see and message those who join a group for the first time would be far more valuable than the current join/leave events. At the moment there is no awareness of adds/drops from a group which seems to totally miss a great opportunity for interaction from the bot.

**Comment by be-hase** [comment]
Thanks for your feedback.
We are now considering this matter.
Please wait.

**Comment by bottsjw** [comment]
Thank you, @be-hase . it would be exceptional if the LINE bot could greet new arrivals to a group intelligently. At the moment.. someone joins and there is silence because the API doesn't allow us to detect the join.
Hope this makes sense. Again, appreciate your help making this feature happen. As important, the "leave" event would be great but having the "join" event would be outstanding first step.

**Comment by bottsjw** [comment]
@be-hase any progress with this? We're struggling with the join/leave event as it is designed. There is a growing need for the "join" event as described above as well as leave.
Thanks.

**Comment by be-hase** [comment]
@bottsjw 
Sorry for the late reply.
As a result of internal consideration, join / leave event deals only with bot itself.
