### ISSUE TITLE
run scheduler doesn't work?

### ISSUE THREAD

**Issue by dyseo** [line/line-bot-sdk-python#210]
I just used bot line, and I want to make a scheduled bot that will give news to the user every time at the set time (for example every 5 minutes) here I am using the `https: // schedule.readthedocs.io` module, hosted via` heroku` with the `flask` ​​framework

and here is my example code:
```python

def execute_job(to):
        bot.push_message(to, "Hello")

def do_job(to):
	check = new_col.find_one({"uid": to})
        while check['run']
	        schedule.run_pending()
	        time.sleep(1.8)

@handler.add(MessageEvent, message=TextMessage)
def handler_message(event):
	msg = event.message
	rep = event.reply_token
	text = msg.text
	type = event.source.type
	to = event.source.user_id if type == "user" else event.source.group_id
	if text.startswith("/news"):
               do_job(to)
```
there is returning error:
```
2019-09-28T09:54:35.692428+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/callback" host=bot-linez.herokuapp.com request_id=3f466ca6-b5f9-4a58-9125-f751cd9d48a7 fwd="147.92.150.197" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
```

i try remove schedule so thats it only While true with time.sleep(5) error same
i think this not support for while loop

i dont know how to solved it, so thanks and greate appreciate for any help

**Comment by okue** [comment]
Sorry for the late reply.

In your program, is `handler_message`, which is annotated by `@handler.add`, called by the function annotated by the flask annotation such as `@app.route("/callback", methods=['POST'])`?

Does your flask server returns a response to a Webhook request?

And, this problem is unrelated to bot-sdk.
Please ask a question like this at [developers community](https://www.line-community.me/questions).
