### ISSUE TITLE
Send Requests Through Proxies

### ISSUE THREAD

**Issue by wiamsuri** [line/line-bot-sdk-python#242]
## Problem
Cannot send requests through proxies like so. https://requests.readthedocs.io/en/master/user/advanced/#proxies

## Solution
Add capability to send requests through proxies like so.
```
line_bot_api = LineBotApi(‘YOUR_CHANNEL_ACCESS_TOKEN’, proxies={'http': 'http://10.10.1.10:3128’})
```

I can help contribute such feature.

**Comment by cryeo** [comment]
[`LineBotApi`](https://line-bot-sdk-python.readthedocs.io/en/stable/linebot.html#linebot.api.LineBotApi) accepts custom http client class which implements [`HttpClient`](https://line-bot-sdk-python.readthedocs.io/en/stable/linebot.html#linebot.http_client.HttpClient), so you can use bot api with proxies by defining your own http client class.

Following is quick example:

```py
import requests
from linebot import HttpClient, LineBotApi
from linebot.http_client import RequestsHttpResponse

class RequestsProxyHttpClient(HttpClient):
    def __init__(self, timeout=HttpClient.DEFAULT_TIMEOUT):
        super().__init__(timeout)
        self.proxies = None

    def set_proxies(proxies):
        self.proxies = proxies

    def get(self, url, headers=None, params=None, stream=False, timeout=None):
        response = requests.get(url, headers=headers, params=params, stream=stream, timeout=timeout or self.timeout, proxies=self.proxies)
        return RequestsHttpResponse(response)

    def post(self, url, headers=None, data=None, timeout=None):
        response = requests.post(url, headers=headers, data=data, timeout=timeout or self.timeout, proxies=self.proxies)
        return RequestsHttpResponse(response)

    def delete(self, url, headers=None, data=None, timeout=None):
        response = requests.delete(url, headers=headers, data=data, timeout=timeout or self.timeout, proxies=self.proxies)
        return RequestsHttpResponse(response)

api = LineBotApi('YOUR_CHANNEL_ACCESS_TOKEN', http_client=RequestProxyHttpClient)
api.http_client.set_proxies({'http': 'http://10.10.1.10:3128’})
```

You should pass additional information after instantiation because there is no way to pass them to the constructor of the given http client class  in [`LineBotApi`](https://line-bot-sdk-python.readthedocs.io/en/stable/linebot.html#linebot.api.LineBotApi). (See also https://github.com/line/line-bot-sdk-python/blob/v1.8.0/linebot/api.py#L55-L58)

**Comment by wiamsuri** [comment]
I'm aware of the custom http client and I am currently implementing something very similar to the example you gave. I just thought that it could be integrated right into the api, so other people do not have to create custom http client.
