### ISSUE TITLE
Stop supporting py27, py34, py35

### ISSUE THREAD

**Issue by okue** [line/line-bot-sdk-python#277]
https://pypistats.org/packages/line-bot-sdk indicates very few users use this sdk with `py27`, `py34`, `py35`.

If there is no problem, we want to stop supporting `py27`, `py34`, `py35`.
We can start to use new features such as asyncio, type hints :)

(Asycnio is discussed at https://github.com/line/line-bot-sdk-python/issues/101)

**Comment by o926428377** [comment]
Although there were few users download the sdk `py27`, `py34`, `py35`, I though lots of users are still using some legacy sdk without update.
Suggest to monitor Line API Server if it could detect what the python version from request source.

**Comment by CircleOnCircles** [comment]
I think the development could be start right away. 
Old users could just pin the package version.
since python lib version and line api version is independent of each other.

I use `fastapi` on my projects, `asyncio, type hints` are going to be benefit for me and all majorities as the stats suggest.

**Comment by tokuhirom** [comment]
https://endoflife.date/python
It was deprecated about 10 months ago. It's time to deprecate it.

**Comment by tokuhirom** [comment]
It was already deprecated :) https://github.com/line/line-bot-sdk-python/commit/02a23fbb2ca7f0df5afacd4df586547801757ef8
