### ISSUE TITLE
Plaintext `true` in JSON output of Flex Message Simulator

### ISSUE THREAD

**Issue by lahdjirayhan** [line/line-bot-sdk-python#291]
## Documentation

JSON output (from LINE Bot Designer and Flex Message Simulator) can contain a plaintext `true`, e.g.:
```
{
    "type": "text",
    "text": "Miraina Tower, 4-1-6 Shinjuku, Tokyo",
    "wrap": true,
    "color": "#666666",
    "size": "sm",
    "flex": 5
}
```
It is different from Python's reserved word `True`, and is not a string `'true'` either. It needs to be clarified whether a JSON output can ALWAYS be copy-pasted directly as a dict input to FlexSendMessage, in light of this issue. And if it can't, what is the correct approach? Changing to `True` or to `'true'`?

**Comment by cryeo** [comment]
Thank you for pointing out. 

>  It needs to be clarified whether a JSON output can ALWAYS be copy-pasted directly as a dict input to FlexSendMessage, in light of this issue.

The notation of Python dictionary is partially JSON-like but is not the same. So, you can't **ALWAYS** use JSON generated from Flex Message Simulator directly except for some specific cases (e.g. JSON does not have boolean values)

We have confirmed that our README contains incorrect information such as
> Thus, You can send a JSON designed with Flex Message Simulator. (from https://github.com/line/line-bot-sdk-python#flexsendmessage)

Sorry for the confusion.

> And if it can't, what is the correct approach? Changing to True or to 'true'?

The following approaches are possible. 
Note that 3 is not recommended because it is so tricky

1. Convert JSON to dictionary notation manually
   - e.g. change JSON true to Python `True`

2. Pass deserialized JSON by `json.loads` to `FlexSendMessage#contents`
```python3
flex_message_json = """
<JSON generated by Flex Message Simulator>
"""
flex_message = FlexSendMessage(alt_text="<alt text>", contents=json.loads(flex_message_json))
```

3. Define true, false variable and copy-paste JSON (not recommended)
```python3
true, false = True, False
flex_message = FlexSendMessage(alt_text="<alt text>", contents=<JSON generated by Flex Message Simulator>)
```
