### ISSUE TITLE
 how to send a message twice

### ISSUE THREAD

**Issue by IlhamriSKY** [line/line-bot-sdk-python#67]
How to send a message twice and pop up a new message bubble.

I've tried with "\ n" but it does not bring up a new message balloon.

**Comment by okdtsk** [comment]
You may use `reply_message`, which uses `replyToken` and this token is valid only once.
Once you use this token, this token is recognized as invalid by LINE Messaging API server.

You should use `push_message` instead of `reply_message`.
But push message request is limited to certain plans so you should check LINE@ plan page.

* Send Reply Message: https://developers.line.me/en/docs/messaging-api/reference/#send-reply-message
* Send Push Message: https://developers.line.me/en/docs/messaging-api/reference/#send-push-message
* LINE@ Plan (Indonesian): http://at.line.me/id/plan

If you are using Developer Trial, you can use Push Message API. let's try this :octocat:

**Comment by IlhamRiski** [comment]
means we can not get two messages at once from send a single message to the bot?

**Comment by okdtsk** [comment]
Yes, each API request corresponds each message (balloon).
If you want to know the detail of Messaging API itself, not each programming language's sdk, you should ask at this repo https://github.com/line/line-bot-faq .

**Comment by LinTim** [comment]
I think this is what you want:

```
line_bot_api.reply_message(
    reply_token, [
    TextSendMessage(text='Hello World!'),
    TextSendMessage(text='Hello World!')
    ]
    )
```
